# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsMagic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_file', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
