# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidDocumentsMagic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_file', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=400, unique=True)),
                ('mimetype', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentsMagic',
        ),
    ]
