# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0002_auto_20171126_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androiddocumentsmagic',
            old_name='magic_file',
            new_name='ftype',
        ),
        migrations.RenameField(
            model_name='androiddocumentsmagic',
            old_name='mimetype',
            new_name='magicfile',
        ),
    ]
