# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0005_androiddocumentsmagic_app_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androiddocumentsmagic',
            name='app_hash',
        ),
    ]
