# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0006_remove_androiddocumentsmagic_app_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='androiddocumentsmagic',
            name='app_hash',
            field=models.CharField(default=1212, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
