# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0007_androiddocumentsmagic_app_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAboutPacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packername', models.CharField(max_length=100, unique=True)),
                ('packer_url', models.URLField()),
                ('resource', models.URLField()),
            ],
        ),
    ]
