# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0008_informationaboutpacker'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutpacker',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
