# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0009_informationaboutpacker_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationaboutpacker',
            old_name='packer_url',
            new_name='packerurl',
        ),
    ]
