# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0011_auto_20171130_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidInformation',
            fields=[
                ('description', models.TextField(blank=True, max_length=5000)),
                ('ahash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='android.AndroidDocumentsMagic')),
            ],
        ),
    ]
