# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0012_androidinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidinformation',
            name='ahash',
        ),
        migrations.AddField(
            model_name='androidinformation',
            name='appid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='android.AndroidDocumentsMagic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='androidinformation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
