# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0013_auto_20171130_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidinformation',
            name='appid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
