# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0014_auto_20171130_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidinformation',
            name='packerinfo',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
