# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0015_androidinformation_packerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidinformation',
            name='packerinfo',
            field=models.CharField(max_length=100),
        ),
    ]
