# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('mtype', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('url', models.URLField()),
                ('num_of_binary', models.PositiveSmallIntegerField()),
                ('num_of_dec', models.PositiveSmallIntegerField()),
                ('num_of_source', models.PositiveSmallIntegerField()),
                ('binary_path', models.FilePathField()),
                ('dec_path', models.FilePathField()),
                ('og_source_path', models.FilePathField()),
            ],
        ),
    ]
