# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoinformation',
            name='date_found',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repoinformation',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='repoinformation',
            name='mname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repoinformation',
            name='mtype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repoinformation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
