# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20171126_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoinformation',
            name='binary_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repoinformation',
            name='dec_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repoinformation',
            name='og_source_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
